# Generated by Django 5.1.1 on 2024-09-08 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('price', models.FloatField()),
                ('rating', models.IntegerField()),
                ('oldprice', models.FloatField()),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
